/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSocialRouteImport } from './routes/_authed/social'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedFlowpayRouteImport } from './routes/_authed/flowpay'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSocialRoute = AuthedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFlowpayRoute = AuthedFlowpayRouteImport.update({
  id: '/flowpay',
  path: '/flowpay',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthedCalendarRoute
  '/flowpay': typeof AuthedFlowpayRoute
  '/home': typeof AuthedHomeRoute
  '/profile': typeof AuthedProfileRoute
  '/social': typeof AuthedSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthedCalendarRoute
  '/flowpay': typeof AuthedFlowpayRoute
  '/home': typeof AuthedHomeRoute
  '/profile': typeof AuthedProfileRoute
  '/social': typeof AuthedSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/flowpay': typeof AuthedFlowpayRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/social': typeof AuthedSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/flowpay'
    | '/home'
    | '/profile'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/flowpay'
    | '/home'
    | '/profile'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/_authed/calendar'
    | '/_authed/flowpay'
    | '/_authed/home'
    | '/_authed/profile'
    | '/_authed/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/social': {
      id: '/_authed/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthedSocialRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/flowpay': {
      id: '/_authed/flowpay'
      path: '/flowpay'
      fullPath: '/flowpay'
      preLoaderRoute: typeof AuthedFlowpayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedFlowpayRoute: typeof AuthedFlowpayRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSocialRoute: typeof AuthedSocialRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedFlowpayRoute: AuthedFlowpayRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSocialRoute: AuthedSocialRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
